<?php
/**
 * @file copelandia_user.module
 * Hook implementations for copelandia_user module.
 */

/**
 * Implements hook_menu().
 */
function copelandia_user_menu() {
  $items['api/v1/user/register'] = array(
    'page callback' => 'copelandia_user_register',
    'file' => 'copelandia_user.pages.inc',
    'access callback' => TRUE,
    'delivery callback' => 'copelandia_user_register_deliver',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Delivery callback for registering a user.
 */
function copelandia_user_register_deliver($response) {
  return drupal_json_output($response);
}
